mysql:
  build: ./mysql
  environment:
    MYSQL_ROOT_PASSWORD: admin
  volumes:
    - ./dbData:/var/lib/mysql
    - /etc/localtime:/etc/localtime:ro

phpfpm:
  build: ./phpfpm
  volumes:
    - ./www:/var/www/html
    - /etc/localtime:/etc/localtime:ro
  links:
    - mysql:mysql
  entrypoint: /etc/services.sh

nginx:
  build: ./nginx
  volumes:
    - ./www:/var/www/html
    - /etc/localtime:/etc/localtime:ro
  environment:
    VIRTUAL_HOST: ag2.local.lcl
  links:
    - phpfpm:php

proxy:
  image: jwilder/nginx-proxy
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
    - /etc/localtime:/etc/localtime:ro
  ports:
    - '80:80'
